server:
  port: 9081
  servlet:
    context-path: /SHMap
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

#地图服务配置
hndistmap:
  mapserver: http://127.0.0.1:8088/cgi-bin/mapserv
  3dserver: http://127.0.0.1:8080/3DServer/
  iotserver: http://127.0.0.1:8099/iotServer/
  serverpath: /opt/homebrew/var/www/

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 日志配置
logging:
  level:
    com.hndist: debug
    org.springframework: error
    springfox: error